version: '3.4'

services:
  db:
    image: samples/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: orders
