apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai
spec:
  type: conversation.openai
  metadata:
    - name: key
      value: <YOUR_API_KEY>
    - name: model
      value: gpt-4-turbo
    - name: cacheTTL
      value: 10m