data:
  AzureWebJobsStorage: CONNECTION_STRING_B64
  FUNCTIONS_WORKER_RUNTIME: bm9kZQ==
apiVersion: v1
kind: Secret
metadata:
  name: javascript-function-subscriber
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-function-subscriber
  namespace: default
  labels:
    app: javascript-function-subscriber
  annotations:
    osiris.deislabs.io/enabled: true
    osiris.deislabs.io/minReplicas: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-function-subscriber
  template:
    metadata:
      labels:
        app: javascript-function-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "javascript-function-subscriber"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: javascript-function-subscriber
        image: IMAGE_NAME
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: MyTopic
        - name: AzureFunctionsJobHost__functions__1
          value: Subscribe
        envFrom:
        - secretRef:
            name: javascript-function-subscriber
---

