kind: Secret
metadata:
  name: csharp-function-subscriber
  namespace: default
data:
  AzureWebJobsStorage: CONNECTION_STRING_B64
apiVersion: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-function-subscriber
  labels:
    app: csharp-function-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-function-subscriber
  template:
    metadata:
      labels:
        app: csharp-function-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "csharp-function-subscriber"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: csharp-function-subscriber
        image: IMAGE_NAME
        ports:
        - containerPort: 80
        imagePullPolicy: Always