@apphost=http://localhost:5260

### Start the OrderWorkflow workflow
# @name startWorkflowRequest
@orderId={{$guid}}
POST {{ apphost }}/start
Content-Type: application/json

{
    "id": "{{orderId}}",
    "orderItem" : {
        "productId": "RBD001",
        "productName": "Rubber Duck",
        "quantity": 10,
        "totalPrice": 15.00
    },
    "customerInfo" : {
        "id" : "Customer1",
        "country" : "The Netherlands"
    }
}

### Get the workflow status
@instanceId={{startWorkflowRequest.response.headers.Location}}
@daprHost=http://localhost:3560
GET {{ daprHost }}/v1.0/workflows/dapr/{{ instanceId }}