named:
	curl -i --request POST http://localhost:8080/start && curl -i --request GET http://localhost:8080/output

patched:
	curl -i --request POST http://localhost:8080/start-patch && curl -i --request GET http://localhost:8080/output-patch




