version: '3.4'

services:
  db:
    image: samples/postgres
    container_name: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: orders
