# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Docker login

on:
  push:
    branches:
      - master

jobs:
  build:
    name: docker login
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_REGISTRY_ID }} -p ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: check pull rate limit
        run: |
          curl --user '${{ secrets.DOCKER_REGISTRY_ID }}:${{ secrets.DOCKER_REGISTRY_PASS }}' "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" -s | jq -r .