#
# Copyright 2023 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Validate csharp quickstart

on:
  push:
    branches:
      - mac-test
  pull_request:
    branches:
      - mac-test

jobs:
  validate:
    name: Validate C# quickstart on Apple Silicon
    runs-on: macos-latest-xlarge
    timeout-minutes: 130
    steps:
      - name: Check out code 
        uses: actions/checkout@v2
      
      - name: Load environment variables
        uses: artursouza/export-env-action@v2
        with:
          envFile: './.github/env/global.env'
          expand: 'true'
      
      - name: Install podman
        timeout-minutes: 15
        run: |
          curl -sL -o podman.pkg https://github.com/containers/podman/releases/download/v${{ env.PODMAN_VERSION }}/podman-installer-macos-arm64.pkg
          sudo installer -pkg podman.pkg -target /
          export PATH=/opt/podman/bin:$PATH
          echo "/opt/podman/bin" >> $GITHUB_PATH
          sudo podman-mac-helper install
          podman machine init
          podman machine start --log-level debug
          echo "CONTAINER_RUNTIME=podman" >> $GITHUB_ENV
      
      - name: Install podman-compose
        run: |
          sudo pip3 install podman-compose
      
      - name: Create symbolic link between Podman and Docker
        run: |
          sudo ln -s $(which podman) /usr/local/bin/docker
          sudo ln -s $(which podman-compose) /usr/local/bin/docker-compose
      
      - name: Install .NET Core 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            8.0.x
      
      - name: Set up Dapr CLI
        run: wget -q ${{ env.DAPR_INSTALL_URL }}/install.sh -O - | /bin/bash -s ${{ env.DAPR_CLI_VERSION }}
      
      - name: Install Dapr
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          dapr init --runtime-version=${{ env.DAPR_RUNTIME_VERSION }}
          dapr --version 
      
      - name: Install utilities dependencies
        run: |
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
          pip3 install setuptools wheel
          pip3 install mechanical-markdown
      
      - name: Validate building blocks with C#
        run: |
          variants=("http" "sdk")
          building_blocks=$(find . -maxdepth 1 -mindepth 1 -type d)
          for building_block in $building_blocks; do
            for variant in "${variants[@]}"
            do
              if [ ! -d "$building_block/csharp/$variant" ]; 
              then
                echo "$building_block/csharp/$variant does not exist."
              else
                pushd $building_block/csharp/$variant
                echo "Validating $building_block/csharp/$variant quickstart"
                make validate 
                popd
              fi
            done
          done
      
      - name: Linkcheck README.md
        run: |
          make validate